### ISSUE TITLE
2019.07.29

### ISSUE THREAD

**Issue by Hyejoojjang** [kuai-jjang/Study-Log#1]
<책읽기>
- 8월 1주차: 4~6장
- 8월 2주차: 7~8장
- 8월 3주차: 9~10장
- 8월 4주차: 11~12장
- 9월 1주차: 13~14장

**Comment by Hyejoojjang** [comment]
**1. TF-IDF**
https://github.com/kuai-jjang/Study-Log/blob/master/ch4_5_tfidf.ipynb
- 후기가 적은 과목의 경우, 유관성이 낮은 곳에 위치해있는 것을 보임
- 1학점 과목을 제외하고 다시 분석해봐도 좋을 것같음


**2. 다른 방법도 사용하기** _혜주 민주_
- FastText
- GloVe


**3. 데이터 정리하기** _성윤 한동_
- Json 파일 업로드해서 합치기 or GCP 위에서 처음부터 크롤링하기
- 테스트용으로 1) 강의평이 많고, 2) 최신 데이터 등등!

**Comment by Hyejoojjang** [comment]
> **1. TF-IDF**
> https://github.com/kuai-jjang/Study-Log/blob/master/ch4_5_tfidf.ipynb
> 
> * 후기가 적은 과목의 경우, 유관성이 낮은 곳에 위치해있는 것을 보임
> * 1학점 과목을 제외하고 다시 분석해봐도 좋을 것같음
> 
> **2. 다른 방법도 사용하기** _혜주 민주_
> 
> * FastText
> * GloVe
> 
> **3. 데이터 정리하기** _성윤 한동_
> 
> * Json 파일 업로드해서 합치기 or GCP 위에서 처음부터 크롤링하기
> * 테스트용으로 1) 강의평이 많고, 2) 최신 데이터 등등!

**Comment by Jeon-Minju** [comment]
> <책읽기>
> 
> * 8월 1주차: 4~6장
> * 8월 2주차: 7~8장
> * 8월 3주차: 9~10장
> * 8월 4주차: 11~12장
> * 9월 1주차: 13~14장

**Comment by JeongSeong** [comment]
> <책읽기>
> 
> * 8월 1주차: 4~6장
> * 8월 2주차: 7~8장
> * 8월 3주차: 9~10장
> * 8월 4주차: 11~12장
> * 9월 1주차: 13~14장
